# ===========================
# Persistent Volume (PV)
# ===========================
apiVersion: v1
kind: PersistentVolume
metadata:
  name: java-db-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual-storage
  hostPath:
    path: /mnt/data/mysql

---
# ===========================
# Persistent Volume Claim (PVC)
# ===========================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: java-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual-storage
  resources:
    requests:
      storage: 5Gi

---
# ===========================
# StatefulSet
# ===========================
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: java-db
spec:
  serviceName: java-db
  replicas: 1
  selector:
    matchLabels:
      app: java-db
  template:
    metadata:
      labels:
        app: java-db
    spec:
      serviceAccountName: argocd-java-db
      imagePullSecrets:
        - name: ecr-creds
      containers:
      - name: mysql-db
        image: 772683617793.dkr.ecr.us-east-1.amazonaws.com/java-proj:db01
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: java-db-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: java-db-storage
        persistentVolumeClaim:
          claimName: java-db-pvc

